#!/bin/sh

##############################################################################
# Gradle start up script for POSIX generated by Gradle.
##############################################################################

APP_NAME="Gradle"
APP_BASE_NAME=`basename "$0"`
DIRNAME=`dirname "$0"`
GRADLE_HOME="$DIRNAME"

CLASSPATH=$GRADLE_HOME/gradle/wrapper/gradle-wrapper.jar

JAVA_HOME="${JAVA_HOME:-/usr}"
JAVA_EXE="$JAVA_HOME/bin/java"

exec "$JAVA_EXE" -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
