name: Build and Release

on:
  workflow_dispatch:
#    inputs:
#      version:
#        description: 'Release version'
#        required: true

permissions:
  contents: write

env:
  GRADLE_OPTS: '-Dorg.gradle.parallel=true -Dorg.gradle.caching=true'

jobs:
  project-metadata:
    name: Prepare ENV
    runs-on: ubuntu-24.04
    outputs:
      version: ${{ steps.version.outputs.version }}
      date: ${{ steps.date.outputs.date }}
    steps:
      - uses: actions/checkout@v6
      - id: name
        name: Extract project name
        run: |
          PROJECT_NAME=$(grep -Po '\brootProject\.name\s*=\s*"\K.*?(?=")' settings.gradle.kts)
          if [ -z "PROJECT_NAME" ]; then echo "Project name not found!" && exit 1; fi
          echo "project_name=PROJECT_NAME" >> $GITHUB_OUTPUT
      - id: version
        name: Extract project version
        run: |
          PROJECT_VERSION=$(grep -Po '\bversion\s*=\s*"\K.*?(?=")' build.gradle.kts)
          if [ -z "PROJECT_VERSION" ]; then echo "Project version not found!" && exit 1; fi
          echo "project_version=PROJECT_VERSION" >> $GITHUB_OUTPUT
      - id: date
        name: Extract current date
        run: echo "date=$(date +%Y%m%d)" >> $GITHUB_OUTPUT

  docker-jvm:
    name: Build Docker JVM
    runs-on: ubuntu-24.04
    needs: project-metadata
    steps:
      - name: Prepare repository
        uses: actions/checkout@v6
      - name: Prepare JDK
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: temurin
          cache: gradle
      - name: Prepare Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Build
        run: ./gradlew assemble
      - name: Login DockerHub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push Docker
        uses: docker/build-push-action@v7
        with:
          build-args: |
            PROJECT_NAME=${{ env.PROJECT_NAME }}
            PROJECT_VERSION=${{ env.PROJECT_VERSION }}
          file: docker/Dockerfile.jvm
          push: true
          tags: |
           ${{ env.REGISTRY_PATH }}:${{ env.PROJECT_VERSION }}-${{ needs.project-metadata.outputs.date }}
           ${{ env.REGISTRY_PATH }}:latest
        env:
          PROJECT_NAME: ${{ needs.project-metadata.outputs.project_name }}
          PROJECT_VERSION: ${{ needs.project-metadata.outputs.project_version }}
          REGISTRY_PATH: ${{ vars.DOCKER_HUB_USERNAME }}/${{ env.PROJECT_NAME }}

  docker-native:
    name: Build Docker Native-image
    runs-on: ubuntu-24.04
    needs: project-metadata
    steps:
      - name: Prepare repository
        uses: actions/checkout@v6
      - name: Prepare GraalVM
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: graalvm
          cache: gradle
      - name: Prepare Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Build
        run: ./gradlew nativeCompile
      - name: Login DockerHub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push Docker
        uses: docker/build-push-action@v7
        with:
          build-args: |
            PROJECT_NAME=${{ env.PROJECT_NAME }}
          file: docker/Dockerfile.native
          push: true
          tags: |
            ${{ env.REGISTRY_PATH }}:native-${{ env.PROJECT_VERSION }}-${{ needs.project-metadata.outputs.date }}
        env:
          PROJECT_NAME: ${{ needs.project-metadata.outputs.project_name }}
          PROJECT_VERSION: ${{ needs.project-metadata.outputs.project_version }}
          REGISTRY_PATH: ${{ vars.DOCKER_HUB_USERNAME }}/${{ env.PROJECT_NAME }}

  distr-jar:
    name: Build Jar Distribution
    runs-on: ubuntu-24.04
    needs: project-metadata
    steps:
      - name: Prepare repository
        uses: actions/checkout@v6
      - name: Prepare JDK
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: temurin
          cache: gradle
      - name: Prepare Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Build
        run: ./gradlew assemble
      - name: Upload Uber-Jar
        uses: actions/upload-artifact@v7
        with:
          name: distr-jar
          path: build/libs/${{ needs.project-metadata.outputs.project_name }}-${{ needs.project-metadata.outputs.project_version }}-all-optimized.jar
          overwrite: true

  distr-native:
    name: Build Native Executable Distribution
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-2025]
    runs-on: ${{ matrix.os }}
    needs: project-metadata
    steps:
      - name: Prepare repository
        uses: actions/checkout@v6
      - name: Prepare GraalVM
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: graalvm
          cache: gradle
      - name: Prepare Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Build
        run: ./gradlew nativeCompile
      - name: Upload Native Executable (Linux)
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v7
        with:
          name: distr-native-linux
          path: build/native/nativeCompile/${{ needs.project-metadata.outputs.project_name }}
          overwrite: true
      - name: Upload Native Executable (Windows)
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v7
        with:
          name: distr-native-win
          path: build/native/nativeCompile/${{ needs.project-metadata.outputs.project_name }}.exe
          overwrite: true

  craete-tag:
    name: Create Tag
    runs-on: ubuntu-24.04
    needs: [ project-metadata, distr-jar, distr-native ]
    steps:
      - name: Prepare repository
        uses: actions/checkout@v6
      - name: Config Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
      - name: Push Tag
        run: |
          git tag -a ${{ env.PROJECT_VERSION }} -m "Beta version ${{ env.PROJECT_VERSION }}"
          git push origin ${{ env.PROJECT_VERSION }}
        env:
          PROJECT_VERSION: ${{ needs.project-metadata.outputs.project_version }}

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-24.04
    needs: [ project-metadata, create-tag ]
    steps:
      - name: Prepare repository
        uses: actions/checkout@v6
      - name: Download All Distributions
        uses: actions/download-artifact@v8
        with:
          path: distribution
          merge-multiple: true
      - name: Rename All Distributions
        working-directory: distribution
        run: |
          mv distr-jar ${{ env.PROJECT_NAME }}-${{ env.PROJECT_VERSION }}.jar
          mv distr-native-linux ${{ env.PROJECT_NAME }}-${{ env.PROJECT_VERSION }}
          mv distr-native-win ${{ env.PROJECT_NAME }}-${{ env.PROJECT_VERSION }}.exe
        env:
          PROJECT_NAME: ${{ needs.project-metadata.outputs.project_name }}
          PROJECT_VERSION: ${{ needs.project-metadata.outputs.project_version }}
      - name: Upload GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          prerelease: true
          files: |
            distribution/**
          name: Release ${{ needs.project-metadata.outputs.project_version }}
          generate_release_notes: true
