name: Check Tests

on:
  push:
    branches:
      - develop
    paths:
      - 'src/**'
      - 'build.gradle.kts'
      - 'settings.gradle.kts'
      - 'gradle.properties'
      - 'gradlew'
      - 'gradlew.bat'
      - 'gradle/wrapper/**'
      - 'docker/**'

env:
  GRADLE_OPTS: '-Dorg.gradle.parallel=true -Dorg.gradle.caching=true'

jobs:
  test:
    name: Unit testing
    runs-on: ubuntu-24.04
    steps:
      - name: Prepare repository
        uses: actions/checkout@v6
      - name: Prepare JDK
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: temurin
          cache: gradle
      - name: Prepare Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Run tests
        run: ./gradlew test
